export const INCREMENT_COUNTER="INCREMENT_COUNTER"
export const DECREMENT_COUNTER="DECREMENT_COUNTER"
export const GET_MEDISION="GET_MEDISION"
export const LOADING_MEDICINES="LOADING_MEDICINES"
export const ERROR_MEDICINES="ERROR_MEDICINES"
export const POST_MEDICINES="POST_MEDICINES"
export const DELETE_MEDICINES="DELETE_MEDICINES"
export const UPDATE_MEDICINES="UPDATE_MEDICINES"
//saga//
export const SIGNUP_USER="SIGNUP_USER"
export const EMAIL_VEREFICATION = "EMAIL_VEREFICATION"

//alert//
export const SET_ALRET ="SET_ALRET"
export const RESET_ALRET= "RESET_ALRET"